name: counting
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.2.4
  - python=3.9.7
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - argparse==1.4.0
    - blis==0.7.5
    - catalogue==2.0.6
    - charset-normalizer==2.0.10
    - click==8.0.3
    - cycler==0.11.0
    - cymem==2.0.6
    - einops==0.3.2
    - fastai==2.5.3
    - fastcore==1.3.27
    - fastdownload==0.0.5
    - fastprogress==1.0.0
    - fonttools==4.28.5
    - h5py==3.6.0
    - idna==3.3
    - imageio==2.13.5
    - jinja2==3.0.3
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - langcodes==3.3.0
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - murmurhash==1.0.6
    - networkx==2.6.3
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandas==1.3.5
    - pathy==0.6.1
    - preshed==3.0.6
    - pydantic==1.8.2
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==6.0
    - requests==2.27.1
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sklearn==0.0
    - smart-open==5.2.1
    - spacy==3.2.1
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - thinc==8.0.13
    - threadpoolctl==3.0.0
    - tifffile==2021.11.2
    - torchinfo==1.6.1
    - tqdm==4.62.3
    - typer==0.4.0
    - urllib3==1.26.7
    - wasabi==0.9.0
    - albumentations
